### ISSUE TITLE
add "walkthrough"

### ISSUE THREAD

**Issue by learnedhoof** [mozilla/ipquest#12]
text that discusses each part of the game and explains in more detail what's happening and the "lesson" behind it

**Comment by learnedhoof** [comment]
i will write the text but will need help from @potch to get it integrated into the page via smart use of css etc :)

**Comment by learnedhoof** [comment]
@potch could you help me by adding a "collapsible" section in index.html for me to start writing this?

**Comment by potch** [comment]
I added a collapsible section for a walkthrough- just change the content where you see WALKTHROUGH GOES HERE
