### ISSUE TITLE
Patentquest isn't secure over HTTPS

### ISSUE THREAD

**Issue by iankronquist** [mozilla/ipquest#21]
Firefox gives an error when attempting to access https://patentquest.mozilla.org/
<img width="1436" alt="screen shot 2016-05-30 at 00 49 47" src="https://cloud.githubusercontent.com/assets/5192353/15643159/a3a45d2e-2600-11e6-880a-7ddb50c53bf4.png">

**Comment by iankronquist** [comment]
This also interacts poorly with https everywhere.

**Comment by learnedhoof** [comment]
i'll check with ryan watson on this.

**Comment by learnedhoof** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1277307
