### ISSUE TITLE
Improve dialogue "trigger" system to be more intentional

### ISSUE THREAD

**Issue by learnedhoof** [mozilla/ipquest#6]

**Comment by potch** [comment]
dialogues are now mostly started with the spacebar. some dialogue trees "interrupt" you - like when you try to leave town the first time. I haven't yet added a visual indicator for when you're in range- working on a little graphic now.

**Comment by learnedhoof** [comment]
cool, are those changes committed to master?

i think the visual indicator is low priority..., especially since group dialogues won't need/want an indicator.

**Comment by potch** [comment]
There's now a little dialogue bubble that pops up when you come upon someone who can talk to you and is waiting for spacebar! seems to work nicely.
